### ISSUE TITLE
SimpleMultisig: style suggestion: remove `require` collation

### ISSUE THREAD

**Issue by veox** [christianlundkvist/simple-multisig#11]
[This line](https://github.com/christianlundkvist/simple-multisig/blob/1d0ce82e3462f5840cf84643779da8c109c1e7cd/contracts/SimpleMultiSig.sol#L10), but also others:

``` solidity
require(owners_.length <= 10 && threshold_ <= owners_.length && threshold_ != 0);
```

... collates several checks into one, which IMO is a bad practice (the expressions eventually grow too complex); and, more importantly, will hinder providing a useful failure message [when that becomes available](https://github.com/ethereum/solidity/issues/1686).

**Comment by christianlundkvist** [comment]
Hmm, I don't really agree that this is too complex, it's a fairly simple expression IMO. I'm not too worried about error messages, app developers should replicate these checks in their frontend code to catch errors before going to the smart contract.
