### ISSUE TITLE
Should allow more signers than threshold

### ISSUE THREAD

**Issue by christoph2806** [christianlundkvist/simple-multisig#13]
I don't see a reason why to limit the number of signatures to `threshold`. 
It could be a common case that more owners than `threshold` decide to sign a transaction, e.g. because they want to express their consensus with the transaction. 

I would therefore propose to change ` require(sigR.length == threshold);` into ` require(sigR.length >= threshold);`

https://github.com/christianlundkvist/simple-multisig/blob/71136f4d9c8c1352ceefaf96dd2ed480b8e5fb60/contracts/SimpleMultiSig.sol#L24

**Comment by christianlundkvist** [comment]
@christoph2806 Hmm, I think this would make it a bit confusing, so I vote against this.

For instance, if the above line is the only change made you can have a bunch of fake signatures at the array indices `threshold`, `threshold+1` etc and the transaction would still go through.

On the other hand if you run the signature verification on the whole array of passed in signatures then it could fail even if we have enough signatures.
