### ISSUE TITLE
Use the call opcode

### ISSUE THREAD

**Issue by ethers** [christianlundkvist/simple-multisig#17]
https://github.com/christianlundkvist/simple-multisig/blob/15a8095818008b0bf3eb901e488d0c5b488513d4/contracts/SimpleMultiSig.sol#L39

Use the call opcode instead like:
https://github.com/uport-project/uport-identity/pull/99/files
because `address.call` pads an extra 32 bytes
https://github.com/ethereum/solidity/issues/2884
(which can cause failure on token contracts such as https://blog.coinfabrik.com/smart-contract-short-address-attack-mitigation-failure/)

**Comment by christianlundkvist** [comment]
@ethers Updated in https://github.com/christianlundkvist/simple-multisig/pull/20. Thanks!
