### ISSUE TITLE
Has this been audited?

### ISSUE THREAD

**Issue by jamesray1** [christianlundkvist/simple-multisig#18]

**Comment by ScJa** [comment]
Only informally by Maurelian AFAIK:
https://github.com/christianlundkvist/simple-multisig/blob/master/maurelian_review.md

**Comment by jamesray1** [comment]
Gnosis multisig has been formally audited.

**Comment by christianlundkvist** [comment]
@jamesray1 Maurelian from [ConsenSys Diligence](https://consensys.net/diligence/) performed the above review but not in an official auditing capacity. I might submit it for a formal audit once [ERC 712](https://github.com/ethereum/EIPs/pull/712) has been finalized at which point I'd like to update the contract to support this standard.

However, the main benefit of this contract is its simplicity, so what I really want to do is to mathematically prove through formal verification that certain things cannot happen (like funds getting locked, or funds being moved without a threshold of signers etc).
