### ISSUE TITLE
Update pragma to 0.4.14

### ISSUE THREAD

**Issue by maurelian** [christianlundkvist/simple-multisig#2]
a properly functioning ecrecover seems pretty essential here:
https://github.com/ethereum/solidity/releases/tag/v0.4.14

**Comment by maurelian** [comment]
Truffle has been updated:

$ truffle version
Truffle v3.4.8 (core: 3.4.8)
Solidity v0.4.15 (solc-js)

**Comment by christianlundkvist** [comment]
Updated to 0.4.15 in https://github.com/christianlundkvist/simple-multisig/pull/6
