### ISSUE TITLE
Web3 and BigNumber are not combined correctly in your Truffle test

### ISSUE THREAD

**Issue by barakman** [christianlundkvist/simple-multisig#33]
At present, Truffle uses Web3 v0.18.4, which in turn uses BigNumber v2.0.0 (or similar).

This means that the Web3 and BigNumber modules are tightly-coupled within Truffle.

Hence, in your Truffle test (file `simplemultisig.js`), you should replace every `new BigNumber` instance passed to a `web3` function, with a call to `web3.toBigNumber` (which creates a BigNumber instance compatible for the Web3 version used by Truffle).

Failure-scenario example:

I am installing:
-    "bignumber.js": "^7.0.0"
-    "truffle": "4.1.11"

Where `bignumber.js` is used in some of my tests for "non-truffle" purposes.

Function `web3.eth.sendTransaction` expects a `value` argument of type BigNumber v2.0.0, which implements function `lessThan`.

However, in BigNumber v7.0.0, the function has been renamed to `isLessThan`.

Hence, in your test (file `simplemultisig.js`), the call to:
```
await web3SendTransaction({from: accounts[0], to: multisig.address, value: web3.toWei(new BigNumber(0.1), 'ether')})
```
Ends with an error:
```
number.lessThan is not a function
```

**Comment by christianlundkvist** [comment]
Thanks, saw the PR!
