### ISSUE TITLE
TestRegistry.sol does not serve as a good testing example

### ISSUE THREAD

**Issue by barakman** [christianlundkvist/simple-multisig#37]
In this contract:
```
pragma solidity ^0.4.18;

// This contract is only used for testing purposes.
contract TestRegistry {

  mapping(address => uint) public registry;

  function register(uint x) payable public {
    registry[msg.sender] = x;
  }

}
```

What exactly is stopping me from calling `function register` directly???

Isn't the purpose of Multi-Sig to restrict permission further than `onlyOwner`?

In this example, the function is not restricted even to `onlyOwner`!

I believe that it would be advisable to:
1. Import [Ownable.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/ownership/Ownable.sol)
2. Inherit from `Ownable`
3. Declare `function register` as `onlyOwner`

Then, in [simplemultisig.js](https://github.com/christianlundkvist/simple-multisig/blob/master/test/simplemultisig.js), after the line
```
let reg = await TestRegistry.new({from: accounts[0]})
```
Add the line:
```
await reg.transferOwnership(multisig.address);
```

Side-note - during execution, an exception is thrown at:
```
await multisig.execute(sigs.sigV, sigs.sigR, sigs.sigS, reg.address, value, data, {from: accounts[0], gasLimit: 1000000})
```
So I have yet to figure out the entire process, but I nevertheless believe that this is the type of capability which should be demonstrated here (i.e., calling a previously-only-owner function via the MultiSig contract).

Update on the side-note above:

The error was thrown because I removed the `payable` keyword from the declaration of `function register`.

After "re-enforcing" it, the test runs to completion.

**Comment by christianlundkvist** [comment]
I don't understand why you would want all this extra complexity? We are simply testing if we can successfully call a function of a smart contract via the multisig and have the function be executed correctly. Maybe it would be good to have a test with of a function with multiple inputs of different types but I don't see where you are going with your question.

**Comment by barakman** [comment]
@christianlundkvist:
Thank you for the quick response.
Kindly explain the point in restricting a function via MultiSig, when anyone can call it directly.

**Comment by christianlundkvist** [comment]
@barakman The point is not to restrict a function via MultiSig, the point is just to test calling any function of any smart contract.

**Comment by barakman** [comment]
@christianlundkvist: I don't quite understand the point of "just to test calling any function of any smart contract", since this is something that one can perform without any additional infrastructure.
