### ISSUE TITLE
Why is "threshold_ >= 0" other than "threshold_ > 0"?

### ISSUE THREAD

**Issue by yimapo** [christianlundkvist/simple-multisig#38]
In the constructor, it is required that "threshold_ >= 0" other than "threshold_ > 0" as follows:
     require(owners_.length <= 10 && threshold_ <= owners_.length && threshold_ >= 0);
I can't think of a use case for threshold == 0.

**Comment by christianlundkvist** [comment]
Good point @yimapo thanks! Not sure where this came from. Indeed we want threshold > 0 to avoid the degenerate case.
