### ISSUE TITLE
Cannot pass the test:  Uncaught Error: exceeds block gas limit

### ISSUE THREAD

**Issue by liangpeili** [christianlundkvist/simple-multisig#8]
I cloned this repository and then ran `npm install` to install the dependencies. But when everything is OK and I ran `npm run test`,  no test case pass. They are all failed because of `Uncaught Error: exceeds block gas limit`.  Can this be solved?

**Comment by ArtemBernatskyy** [comment]
Also interested in this

**Comment by christianlundkvist** [comment]
@liangpeili @ArtemBernatskyy I just tested it with the new updates, can you try again?

**Comment by ArtemBernatskyy** [comment]
Nope, i was manually deploying contract via `Mist`
