### ISSUE TITLE
Why not hardcode values?

### ISSUE THREAD

**Issue by neuhaus** [christianlundkvist/simple-multisig#9]
The goal is for the contract to be "designed to be as simple as possible". Wouldn't it be advantageous to hardcode the `ownersArr` and `threshold` values instead of specifying them as parameters to the constructor? :woman_shrugging: 
It would make the code even simpler.

**Comment by christoph2806** [comment]
for a sample implementation of this, see https://github.com/etherisc/simplestWallet

**Comment by neuhaus** [comment]
Great start!
Right now in simplestWallet the code in the `execute` function has to be changed whenever the number of owners and/or the `threshhold` are changed.
Changing it to deal with it automatically would remove a poential source of errors.

**Comment by christianlundkvist** [comment]
Interesting approach! 😃

Hardcoding these values would indeed make the complexity of the constructor go away. Not sure how to deal with that in terms of formal semantics, since I feel you’d have to create a formal specification for each contract with hard coded values 🤔

@christoph2806 nice implementation! Although the indices in the signatures are off by one (goes from 1 to 3 instead of 0 to 2)

**Comment by christoph2806** [comment]
@christianlundkvist fixed it - thank you for heads up! Regarding formal spec: I think you could write a meta-spec which is generic and then you have a template for a proof (like proof by induction). 
@neuhaus The idea is that the wallet is so small that creating a new one is cheap and simple. A UX could completely hide this complexity from the user, giving him the usual "addOwner" / "removeOwner" / "changeThreshold" functionality.
This implementation is thought as a starting point for an insurable wallet, it can't be simple enough for that.

**Comment by neuhaus** [comment]
OK. I think we should strive for a program that asks your for the parameters (owners, threshold) and generates the custom contract.
